"""Adiciona kwh_adjustment a Proposal

Revision ID: 0683eeff22c1
Revises: e9584fba016d
Create Date: 2025-10-31 20:33:08.989016

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0683eeff22c1'
down_revision = 'e9584fba016d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('client', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_client_cpf_cnpj'))
        batch_op.create_index(batch_op.f('ix_client_cpf_cnpj'), ['cpf_cnpj'], unique=True)

    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_product_category'))
        batch_op.create_index(batch_op.f('ix_product_category'), ['category'], unique=False)

    with op.batch_alter_table('proposal', schema=None) as batch_op:
        batch_op.add_column(sa.Column('kwh_adjustment', sa.Integer(), nullable=True))
        batch_op.drop_index(batch_op.f('ix_proposal_creation_date'))
        batch_op.create_index(batch_op.f('ix_proposal_creation_date'), ['creation_date'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('proposal', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_proposal_creation_date'))
        batch_op.create_index(batch_op.f('ix_proposal_creation_date'), ['creation_date'], unique=False)
        batch_op.drop_column('kwh_adjustment')

    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_product_category'))
        batch_op.create_index(batch_op.f('ix_product_category'), ['category'], unique=False)

    with op.batch_alter_table('client', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_client_cpf_cnpj'))
        batch_op.create_index(batch_op.f('ix_client_cpf_cnpj'), ['cpf_cnpj'], unique=True)

    # ### end Alembic commands ###
