"""att0001

Revision ID: 7de130f1d53c
Revises: ed35eb40b74a
Create Date: 2025-12-03 19:34:07.403952

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7de130f1d53c'
down_revision = 'ed35eb40b74a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('client', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_client_timestamp'))
        batch_op.create_index(batch_op.f('ix_client_cpf_cnpj'), ['cpf_cnpj'], unique=True)

    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_product_category'))
        batch_op.create_index(batch_op.f('ix_product_category'), ['category'], unique=False)

    with op.batch_alter_table('proposal', schema=None) as batch_op:
        batch_op.alter_column('kwh_adjustment',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=True)
        batch_op.drop_index(batch_op.f('ix_proposal_status'))
        batch_op.create_index(batch_op.f('ix_proposal_status'), ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('proposal', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_proposal_status'))
        batch_op.create_index(batch_op.f('ix_proposal_status'), ['status'], unique=False)
        batch_op.alter_column('kwh_adjustment',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=True)

    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_product_category'))
        batch_op.create_index(batch_op.f('ix_product_category'), ['category'], unique=False)

    with op.batch_alter_table('client', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_client_cpf_cnpj'))
        batch_op.create_index(batch_op.f('ix_client_timestamp'), ['timestamp'], unique=False)

    # ### end Alembic commands ###
