"""empty message

Revision ID: d11313435a07
Revises: 0d6de0809ab5
Create Date: 2025-10-28 18:33:34.536960

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd11313435a07'
down_revision = '0d6de0809ab5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('client', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_client_name'))
        batch_op.create_index(batch_op.f('ix_client_email'), ['email'], unique=False)

    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_url', sa.String(length=255), nullable=True))
        batch_op.drop_index(batch_op.f('ix_product_category'))
        batch_op.create_index(batch_op.f('ix_product_category'), ['category'], unique=False)

    with op.batch_alter_table('proposal', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_proposal_creation_date'))
        batch_op.create_index(batch_op.f('ix_proposal_status'), ['status'], unique=False)

    with op.batch_alter_table('proposal_item', schema=None) as batch_op:
        batch_op.drop_column('total_price')
        batch_op.drop_column('unit_price')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('proposal_item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('unit_price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('total_price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))

    with op.batch_alter_table('proposal', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_proposal_status'))
        batch_op.create_index(batch_op.f('ix_proposal_creation_date'), ['creation_date'], unique=False)

    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_product_category'))
        batch_op.create_index(batch_op.f('ix_product_category'), ['category'], unique=False)
        batch_op.drop_column('image_url')

    with op.batch_alter_table('client', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_client_email'))
        batch_op.create_index(batch_op.f('ix_client_name'), ['name'], unique=False)

    # ### end Alembic commands ###
