"""Adiciona campos de pagamento na proposta

Revision ID: e9584fba016d
Revises: d11313435a07
Create Date: 2025-10-30 10:11:17.994511

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e9584fba016d'
down_revision = 'd11313435a07'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('client', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_client_email'))
        batch_op.create_index(batch_op.f('ix_client_cpf_cnpj'), ['cpf_cnpj'], unique=True)

    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_product_category'))
        batch_op.create_index(batch_op.f('ix_product_category'), ['category'], unique=False)

    with op.batch_alter_table('proposal', schema=None) as batch_op:
        batch_op.add_column(sa.Column('credit_card_installments', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('credit_card_interest_rate', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('financing_installments', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('financing_interest_rate', sa.Float(), nullable=True))
        batch_op.drop_index(batch_op.f('ix_proposal_status'))
        batch_op.create_index(batch_op.f('ix_proposal_creation_date'), ['creation_date'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('proposal', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_proposal_creation_date'))
        batch_op.create_index(batch_op.f('ix_proposal_status'), ['status'], unique=False)
        batch_op.drop_column('financing_interest_rate')
        batch_op.drop_column('financing_installments')
        batch_op.drop_column('credit_card_interest_rate')
        batch_op.drop_column('credit_card_installments')

    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_product_category'))
        batch_op.create_index(batch_op.f('ix_product_category'), ['category'], unique=False)

    with op.batch_alter_table('client', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_client_cpf_cnpj'))
        batch_op.create_index(batch_op.f('ix_client_email'), ['email'], unique=False)

    # ### end Alembic commands ###
