"""Adiciona inflacao energetica

Revision ID: ed35eb40b74a
Revises: 0683eeff22c1
Create Date: 2025-12-03 19:07:06.680364

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ed35eb40b74a'
down_revision = '0683eeff22c1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('client', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_client_cpf_cnpj'))
        batch_op.create_index(batch_op.f('ix_client_timestamp'), ['timestamp'], unique=False)

    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_product_category'))
        batch_op.create_index(batch_op.f('ix_product_category'), ['category'], unique=False)

    with op.batch_alter_table('proposal', schema=None) as batch_op:
        batch_op.add_column(sa.Column('energy_inflation', sa.Float(), nullable=True))
        batch_op.drop_index(batch_op.f('ix_proposal_creation_date'))
        batch_op.create_index(batch_op.f('ix_proposal_status'), ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('proposal', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_proposal_status'))
        batch_op.create_index(batch_op.f('ix_proposal_creation_date'), ['creation_date'], unique=False)
        batch_op.drop_column('energy_inflation')

    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_product_category'))
        batch_op.create_index(batch_op.f('ix_product_category'), ['category'], unique=False)

    with op.batch_alter_table('client', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_client_timestamp'))
        batch_op.create_index(batch_op.f('ix_client_cpf_cnpj'), ['cpf_cnpj'], unique=True)

    # ### end Alembic commands ###
